FROM nginx:alpine
COPY index.html /usr/share/nginx/html/index.html
COPY myStyle.css /usr/share/nginx/html/myStyle.css
COPY logo4.png /usr/share/nginx/html/logo4.png
COPY artistCollabs.html /usr/share/nginx/html/artistCollabs.html
COPY bogo.html /usr/share/nginx/html/bogo.html
COPY contacts.html /usr/share/nginx/html/contacts.html
COPY rarepieces.html /usr/share/nginx/html/rarepieces.html
COPY timer.html /usr/share/nginx/html/timer.html
COPY bogo2.jpg /usr/share/nginx/html/bogo2.jpg
COPY rare.jpg /usr/share/nginx/html/rare.jpg
COPY shoes3.jpg /usr/share/nginx/html/shoes3.jpg